### PR TITLE
Changed deprecated ALIVE by ALIVE_INSTANCE_STATE in code tester [10184]

### PR DESCRIPTION
**Pull request by rsanchez15**
Signed-off-by: RaulSanchez <raul@eprosima.com>

### CODE REVIEW

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/680/)

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/681/)

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/683/)

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/684/)

**Review by EduPonz — APPROVED** [review]

**Pull request merged**
