### PR TITLE
Add loanable sequences API reference [10335]

### PR DESCRIPTION
**Pull request by rsanchez15**
Added API reference for the following classes and structs:
* `LoanableArray`
* `LoanableCollection`
* `LoanableSequence`
* `StackAllocatedSequence`

### CODE REVIEW

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
Instead of adding wrong words to the spelling list, we should fix them in the doxygen instead

**Comment by MiguelCompany** [comment]
> Instead of adding wrong words to the spelling list, we should fix them in the doxygen instead

See eProsima/Fast-DDS#1702

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/712/)

**Review by MiguelCompany — APPROVED** [review]

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/713/)

**Pull request merged**
