### PR TITLE
Update documentation inclusiveness

### PR DESCRIPTION
**Pull request by DaveJarvis**
Revise gendered language to be neutral.

### CODE REVIEW

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/678/)

**Comment by DaveJarvis** [comment]
Looks like this is failing on a spell check.

> Users may easily implement platform modules using the *eProsima Fast DDS* library on their target platforms.

I don't see any spelling mistakes, so is the problem elsewhere?

**Comment by EduPonz** [comment]
These are caused by master branch. They are fixed in #214 . Re-running CI

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/679/)

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/682/)

**Comment by EduPonz** [comment]
@DaveJarvis CI looks green, however, are not signed according to DCO. To solve this, please follow the instructions in [here](https://github.com/eProsima/Fast-RTPS-docs/pull/215/checks?check_run_id=1582846915).

**Review by EduPonz — APPROVED** [review]

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/685/)

**Comment by DaveJarvis** [comment]
Something's wrong with the commit. Dunno. Not worth fixing.

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/686/)

**Comment by EduPonz** [comment]
Hi @DaveJarvis ,

I consider your contribution very much relevant and valid, so I submitted #217 to address it. Thanks a lot for the catch!

**Pull request closed without merging**
