### PR TITLE
Revert master only features <2.0.x> [9910]

### PR DESCRIPTION
**Pull request by MiguelCompany**
This reverts commits 94ba43b637613dcc1353c22d5bd679e3d906612b and 809091995d1955db1d984abfb30dd1460c798b86, that should only be present on `master`

Signed-off-by: Miguel Company <MiguelCompany@eprosima.com>

### CODE REVIEW

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/656/)

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/657/)

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/658/)

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/669/)

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/670/)

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/671/)

**Review by EduPonz — APPROVED** [review]
LGTM

**Pull request merged**
